
version: '3.8'

services:
  testApp:
      build: .
      container_name: testApp
      restart: always
      ports:
      - "5000:5000"
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      ports:
      - "80:80"
      volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
      - testApp